pizzas/urls.py
from django.urls import path

from . import views
from django.conf import settings  
from django.urls import path, include 
from django.conf.urls.static import static  

app_name = 'pizzas'



urlpatterns = [
    path('', views.index, name='index'),
    path('pizzas/', views.pizzas, name='pizzas'),
    path('pizza/<int:pizza_id>/', views.pizza, name='pizza'),
]

pizzeria_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.p_name

class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.CharField(max_length=200)

    def __str__(self):
        return self.topping_name


class Comment(models.Model):
    pizza = models.ForeignKey(Pizza,on_delete=models.CASCADE)
    content = models.TextField(max_length=300)

    def __str__(self):
        return f"Comment by {self.name} on {self.p_name} - {self.time}"

pizzas/views.py
from django.shortcuts import render, redirect

from .models import Pizza
from .forms import *

def index(request):
    return render(request, 'pizzas/index.html')

def pizzas(request):
    pizzas = Pizza.objects.all()
    context = {'Menu': pizzas}
    return render(request, 'pizzas/Menu.html', context)

def pizza(request, pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = Topping.objects.filter(pizza=pizza).order_by('pizza_id')

    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizza.html', context)


def new_comment(request,pizza_id):
    pizza = Pizza.objects.get(id=pizza_id)
    if request.method != 'POST':
        forms = CommentForm()
    else:
        forms = CommentForm(data=request.POST)
        if forms.is_valid():
            new_comment = forms.save(commit=False)
            new_comment.pizza = pizza
            new_comment.save()
            return redirect('pizzas:pizza', pizza_id=pizza_id)
        
    context = {'form':forms, 'pizza':pizza}
    return render(request, 'pizzas/new_comment.html', context)

pizzas/templates/pizzas/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pizzeria</title>
    <style>
        body {
            font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
            margin: 0;
            padding: 0;
            background-color: #060606;
        }

        header {
            background-color: #f51900;
            padding: 10px;
            text-align: center;
        }

        nav {
            text-align: center;
            padding: 10px;
            background-color: #060606;
        }

        nav a {
            color: #060606;
            text-decoration: none;
            margin: 0 10px;
            font-size: 16px;
            transition-property: color;
            transition-duration: 0.2s;
            transition-timing-function: linear;
        }

        nav a:hover {
            text-decoration: underline;
            color: #f51900;
        }

        nav a.active {
            background-color: #f51900;
            padding: 10px;
            border-radius: 5px;
            transition-property: background-color;
            transition-duration: 0.2s;
            transition-timing-function: linear;
        }

        nav a.active:hover,
        nav a.active:focus {
            background-color: #f51900;
        }

        .container {
            max-width: 1000px;
            margin: 0 auto;
            padding: 10px;
        }
    </style>
</head>
<body>
    <header>
        <h1 style="color: white; font-size: 32px;">Howdy, Welcome to <span style="font-weight: bold;">Sanjay's Pizzeria!</span>!</h1>

    </header>

    <nav>
        <a href="{% url 'pizzas:index' %}" class="{% if request.path == '/pizzas/' %}active{% endif %}">Home</a>
        <a href="{% url 'pizzas:pizzas' %}" class="{% if request.path == '/pizzas/pizzas/' %}active{% endif %}">Pizzas</a>
    </nav>

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
    <div style="text-align: center;">
        <h1 style="color: #060606;; font-size: 36px; margin-bottom: 20px;">
            Take a look at our menu of beautifully handcrafted pizzas! 
    </div>


{% endblock content %}

pizzas/templates/pizzas/menu.html
{% extends 'pizzas/base.html' %}

{% block content %}
  <p>Pizzas</p>

  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza.name }}</a>
      </li>
    {% empty %}
      <li>Pizzas are currently unavailable</li>
    {% endfor %}
  </ul>

{% endblock content %}

pizzas/templates/pizzas/new_comment.html
{% extends "pizzas/base.html" %}

{% block content %}

<p><a href="{% url 'pizzas:pizza' pizza.id %}">{{pizza}}</a></p>

<p>Add a comment:</p>

<form action="{% url 'pizzas:new_comment' pizza.id %}" method='post'>

{% csrf_token %}

{{form.as_p}}

<button name="Submit">submit</button>

</form>

{% endblock content %}